spring:
  application:
    name: ingredient-detection-backend
  datasource:
    name: dataSource
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      driver-class-name: org.postgresql.Driver
#      connection-init-sql: SET NAMES utf8mb4
  jackson:
    locale: zh_CN
    time-zone: Asia/Shanghai
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  messages:
    basename: i18n/validation
  cache:
    type: caffeine
#  redis:
#    redisson:
#      config: |
#        singleServerConfig:
#          idleConnectionTimeout: 10000
#          connectTimeout: ${spring.redis.connect-timeout:10000}
#          timeout: ${spring.redis.timeout:3000}
#          retryAttempts: 3
#          retryInterval: 1500
#          password: ${spring.redis.password:null}
#          subscriptionsPerConnection: 1
#          clientName: null
#          address: "redis://${spring.redis.host}:${spring.redis.port}"
#          subscriptionConnectionMinimumIdleSize: 0
#          subscriptionConnectionPoolSize: 50
#          connectionMinimumIdleSize: ${spring.redis.pool.min-idle:0}
#          connectionPoolSize: ${spring.redis.pool.max-idle:8}
#          database: ${spring.redis.database:0}
#          dnsMonitoringInterval: ${spring.redis.pool.time-between-eviction-runs:5000}
#        threads: 16
#        nettyThreads: 32
#        codec: !<org.redisson.codec.MarshallingCodec> {}
#        transportMode: "NIO"
#  autoconfigure:
#    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-prefix: dao.
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

ms:
  spring:
    exception:
      resource-paths: i18n/error
  security:
    exclude-matchers: /api/backend/account/sign-in/**,/api/backend/account/sign-up/**,/stomp/endpoint/**,/api/backend/device/assets/torpedo-car-weight-info,/api/backend/setting/settings/global-variable/**,/api/backend/device/assets/pot/weight
    exclude-get-matchers: /**

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.ByteArray.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
